edition = "2024"
max_width = 79
tab_spaces = 4
hard_tabs = false
newline_style = "Unix"

reorder_imports = true
group_imports = "StdExternalCrate"
imports_granularity = "Crate"
merge_imports = true

use_field_init_shorthand = true
trailing_comma = "Vertical"
match_block_trailing_comma = true
brace_style = "SameLineWhere"
control_brace_style = "AlwaysNextLine"
fn_brace_style = "PreferSameLine"

wrap_comments = true
comment_width = 80
normalize_comments = true

use_small_heuristics = "Max"
blank_lines_upper_bound = 1
